version: '3.9'

services:
  db_pdf_gen_1:
    container_name: db_pdf_gen_1
    image: gvenzl/oracle-free:latest
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: demo_user
      APP_USER_PASSWORD: secret
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
#  rabbitmq:
#    container_name: guava_rabbitmq
#    image: rabbitmq:3.9-management-alpine
#    environment:
#      RABBITMQ_DEFAULT_USER: "admin"
#      RABBITMQ_DEFAULT_PASS: "admin"
#    ports:
#      - "5672:5672"
#      - "15672:15672"