spring:
  application:
    name: pdf-gen-1
  main:
    banner-mode: "off"
  threads:
    virtual:
      enabled: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
  datasource:
    url: jdbc:oracle:thin:@//${ORACLE_DB_HOST:localhost:1521}/FREEPDB1
    username: ${ORACLE_DB_USER:demo_user}
    password: ${ORACLE_DB_PASSWORD:secret}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

      connection-timeout: 30000      # 30 sec
      idle-timeout: 600000           # 10 min
      max-lifetime: 1800000          # 30 min

      keepalive-time: 300000         # 5 min (only checks idle connections)
      validation-timeout: 5000       # 5 sec

      # Monitoring
      leak-detection-threshold: 60000 # 60 sec - memory leak detection

      # Performance
      auto-commit: false             # give Transaction management to Spring

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy #usage?
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate:
        default_schema: DEMO_USER #
        jdbc:
          batch_size: 25             # to Batch insert/update
          batch_versioned_data: true
        order_inserts: true          # Performance increasing
        order_updates: true
        show_sql: true
        format_sql: true
        use_sql_comments: false

jdbc:
  datasource-proxy:
#    query:
#      enable-logging: ${DS_PROXY_ENABLED:true}
    slow-query:
      enable-logging: ${DS_PROXY_ENABLED:true}
    multiline: false

# for Monitoring ve health check
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    health:
      show-details: always

# Production logging
logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.zaxxer.hikari: INFO          # HikariCP connection pool logs
#    org.springframework.web: INFO   # Web request logs
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 9303
